### ISSUE TITLE
ERROR: no module named TGSession

### ISSUE THREAD

**Issue by Tiny-Stark** [Desamod/PawsBot#4]
Traceback (most recent call last):
  File "C:\Users\X\PawsBot\main.py", line 5, in <module>
    from bot.utils import logger
  File "C:\Users\X\PawsBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\X\PawsBot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\X\PawsBot\bot\core\tapper.py", line 19, in <module>
    from ..utils.tg_manager.TGSession import TGSession
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

what should i do?

**Comment by Desamod** [comment]
Check your python version. Must be 3.10

**Comment by Tiny-Stark** [comment]
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 18:46:30) [MSC v.1929 32 bit (Intel)] on win32

is it running for win32?
i can't know, i'm not a programmer

**Comment by Desamod** [comment]
Added support for win32 OS
